### ISSUE TITLE
Separate articles details in a different page

### ISSUE THREAD

**Issue by LeoPenaguin** [OpenEstate/OpenEstate-PHP-Wrapper-WordPress#1]
Hi,

I have an article list on a page wich is generated with the wrapper.

I would like to have the article details page on a different page when I click on an element to have a different header and footer. Is there a way to do that by configuring the plugin ? Or do i have to do it myself with some extra PHP ?

Thanks !

**Comment by pinhead84** [comment]
Hi Leo,

this is currently not possible directly through the plugin configuration. The best approach (without changing the PHP code) from my point of view would be some kind of URL rewriting. You might write a rewrite rule, that checks for certain parameters and redirects to the page you like. I know it's kind of ugly but it should work. ;)

We're currently reworking the whole PHP export feature. You can find the latest development version at [this GitHub page (in the `develop` branch)](https://github.com/OpenEstate/OpenEstate-PHP-Export/tree/develop). This new release provides a lot more options for customization - e.g. each URL can be configured explicitly. If you're familiar with PHP, I would strongly suggest to take a look at the new version. We're also going to integrate it into the next ImmoTool release.

I'm currently working on the WordPress plugin (see branch [phpexport-2.x](https://github.com/OpenEstate/OpenEstate-PHP-Wrapper-WordPress/tree/phpexport-2.x)). The plugin basically already works. I'm going to check, how to integrate your request into the new WordPress plugin.

Best regards.

**Comment by LeoPenaguin** [comment]
Great I'll try it, vielen Dank !
