### ISSUE TITLE
Filter by criteria: brokered

### ISSUE THREAD

**Issue by zensudo** [OpenEstate/OpenEstate-PHP-Wrapper-WordPress#4]
Hey there,

i'm using the php wrapper for Wordpress and i need to show some property references on a second page. I tried to use the shortcode and want to select a filter with "brokered". Unfortunately it seems not working. Does anyone have an idea how to filter these objects?

**Comment by pinhead84** [comment]
Hi.

OpenEstate-ImmoTool doesn't export brokered properties by default. The user must enable this within the software beforehand (tab "search" in the export interface settings). Are you sure, that brokered properties are already transferred to the webspace (take a look at the `data` folder)?

Also you need a filter for the status. I guess by default such a filter is not available in the PHP export environment. You need to add this filter by yourself. If a status filter is present and working, you should be able to use this filter within the WordPress shortcode.

**Comment by zensudo** [comment]
Thanks for your response.

They are transferred and i can see the "status" part in the php files. It seems there is no filter by default. I will try to build some workaround.

Thanks
