### ISSUE TITLE
Change the order of textboxes in the description tab

### ISSUE THREAD

**Issue by zensudo** [OpenEstate/OpenEstate-PHP-Wrapper-WordPress#5]
Hello,

i would like to change the order of the text areas in the "Description" Tab.

For now, the description first starts with "more informations" and is followed by the "short description" of the estate.

Is there any way to change the position? It would be nice if there comes the "short description" first and is followed by "more informations".

**Comment by pinhead84** [comment]
Hello,

inside the export folder on your webspace you can modify the ordering by changing [this line](https://github.com/OpenEstate/OpenEstate-PHP-Export/blob/master-1.7/src/myconfig.php#L66) in the `myconfig.php` file:

```php
class immotool_myconfig
{
    /**
     * Konfiguration der Exposédarstellung überschreiben.
     * @param object $config Konfigurations-Objekt
     */
    public static function load_config_expose(&$config)
    {
        $config->TextOrder = array( 'detailled_description', 'location_description', 'feature_description', 'price_description', 'agent_fee_information', 'additional_information', 'short_description' );
    }
}
```

The only relevant line is `$config->TextOrder` - the rest should already be available. Just rearrange the values inside the array to achieve the ordering you like.

**Comment by zensudo** [comment]
Perfect, you helped me a lot, thank you.
